// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD5td-z8DXyjVstbM_HDIc6qOvW8kQX08',
    appId: '1:856661928406:web:ae33403f1a938e5924dc77',
    messagingSenderId: '856661928406',
    projectId: 'projects-fb0f2',
    authDomain: 'projects-fb0f2.firebaseapp.com',
    storageBucket: 'projects-fb0f2.firebasestorage.app',
    measurementId: 'G-QWN54JSP3X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY4EKVlOZ6mNCg1HPvpdAohS8hNXqG7fE',
    appId: '1:856661928406:android:35fa14d24a98080b24dc77',
    messagingSenderId: '856661928406',
    projectId: 'projects-fb0f2',
    storageBucket: 'projects-fb0f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS1tq03QPLyOYyPl28gKik4-3MRyif44g',
    appId: '1:856661928406:ios:f4a1fd8b8e60341424dc77',
    messagingSenderId: '856661928406',
    projectId: 'projects-fb0f2',
    storageBucket: 'projects-fb0f2.firebasestorage.app',
    iosBundleId: 'com.example.projects',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCS1tq03QPLyOYyPl28gKik4-3MRyif44g',
    appId: '1:856661928406:ios:f4a1fd8b8e60341424dc77',
    messagingSenderId: '856661928406',
    projectId: 'projects-fb0f2',
    storageBucket: 'projects-fb0f2.firebasestorage.app',
    iosBundleId: 'com.example.projects',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAD5td-z8DXyjVstbM_HDIc6qOvW8kQX08',
    appId: '1:856661928406:web:7ee7fbe8ec8ec1fd24dc77',
    messagingSenderId: '856661928406',
    projectId: 'projects-fb0f2',
    authDomain: 'projects-fb0f2.firebaseapp.com',
    storageBucket: 'projects-fb0f2.firebasestorage.app',
    measurementId: 'G-6P7C7E39EC',
  );
}
